INSERT INTO Bd (id, position_in_serie, title, serie_id, publication_date, version) values (-1, 0, 'Le combat ordinaire', -1, '2020-01-01', 0);
INSERT INTO Bd (id, position_in_serie, title, serie_id, publication_date, version) values (-2, 1, 'Les quantités négligeables', -1, '2020-01-01', 0);
INSERT INTO Bd (id, position_in_serie, title, serie_id, publication_date, version) values (-3, 2, 'Ce qui est précieux', -1, '2020-01-01', 0);
INSERT INTO Bd (id, position_in_serie, title, serie_id, publication_date, version) values (-4, 3, 'Planter des clous', -1, '2020-01-01', 0);
INSERT INTO Bd (id, position_in_serie, title, serie_id, publication_date, version) values (-5, 0, 'Ambrosia', -2, '2020-01-01', 0);
INSERT INTO Bd (id, position_in_serie, title, serie_id, publication_date, version) values (-6, 1, 'Hestia', -2, '2020-01-01', 0);
INSERT INTO Bd (id, position_in_serie, title, serie_id, publication_date, version) values (-7, 2, 'Ophidia', -2, '2020-01-01', 0);
INSERT INTO Bd (id, position_in_serie, title, serie_id, publication_date, version) values (-8, 3, '666 I.A.', -2, '2020-01-01', 0);
INSERT INTO Bd (id, position_in_serie, title, serie_id, publication_date, version) values (-9, 0, 'L''héritier', -3, '2020-01-01', 0);
INSERT INTO Bd (id, position_in_serie, title, serie_id, publication_date, version) values (-10, 1, 'Le groupe W', -3, '2020-01-01', 0);
INSERT INTO Bd (id, position_in_serie, title, serie_id, publication_date, version) values (-11, 2, 'O.P.A', -3, '2020-01-01', 0);
INSERT INTO Bd (id, position_in_serie, title, serie_id, publication_date, version) values (-12, 0, 'Intégrale (1,2,3)', -4, '2020-01-01', 0);
INSERT INTO Bd (id, position_in_serie, title, serie_id, publication_date, version) values (-13, 0, 'Le sommeil du monstre', -5, '2020-01-01', 0);
INSERT INTO Bd (id, position_in_serie, title, serie_id, publication_date, version) values (-14, 1, '32 décembre', -5, '2020-01-01', 0);
INSERT INTO Bd (id, position_in_serie, title, serie_id, publication_date, version) values (-15, 2, 'Rendez-vous à Paris', -5, '2020-01-01', 0);
INSERT INTO Bd (id, position_in_serie, title, serie_id, publication_date, version) values (-16, 3, 'Quatre ?', -5, '2020-01-01', 0);