INSERT INTO Bd (id, position_in_serie, title, serie_id) values (-1, 1, 'Le combat ordinaire', -1);
INSERT INTO Bd (id, position_in_serie, title, serie_id) values (-2, 2, 'Les quantités négligeables', -1);
INSERT INTO Bd (id, position_in_serie, title, serie_id) values (-3, 3, 'Ce qui est précieux', -1);
INSERT INTO Bd (id, position_in_serie, title, serie_id) values (-4, 4, 'Planter des clous', -1);
INSERT INTO Bd (id, position_in_serie, title, serie_id) values (-5, 1, 'Ambrosia', -2);
INSERT INTO Bd (id, position_in_serie, title, serie_id) values (-6, 2, 'Hestia', -2);
INSERT INTO Bd (id, position_in_serie, title, serie_id) values (-7, 3, 'Ophidia', -2);
INSERT INTO Bd (id, position_in_serie, title, serie_id) values (-8, 4, '666 I.A.', -2);
INSERT INTO Bd (id, position_in_serie, title, serie_id) values (-9, 1, 'L''héritier', -3);
INSERT INTO Bd (id, position_in_serie, title, serie_id) values (-10, 2, 'Le groupe W', -3);
INSERT INTO Bd (id, position_in_serie, title, serie_id) values (-11, 3, 'O.P.A', -3);
INSERT INTO Bd (id, position_in_serie, title, serie_id) values (-12, 1, 'Intégrale (1,2,3)', -4);
INSERT INTO Bd (id, position_in_serie, title, serie_id) values (-13, 1, 'Le sommeil du monstre', -5);
INSERT INTO Bd (id, position_in_serie, title, serie_id) values (-14, 1, '32 décembre', -5);
INSERT INTO Bd (id, position_in_serie, title, serie_id) values (-15, 1, 'Rendez-vous à Paris', -5);
INSERT INTO Bd (id, position_in_serie, title, serie_id) values (-16, 1, 'Quatre ?', -5);